/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.CoAPMetadata;
import com.lab5e.span.model.Device;
import com.lab5e.span.model.OutputDataMessageOutputMessageType;
import com.lab5e.span.model.UDPMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The output data message contains payload plus metadata for a payload received from a device.
 */
@ApiModel(description = "The output data message contains payload plus metadata for a payload received from a device.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-20T10:26:47.664Z[GMT]")
public class OutputDataMessage {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private OutputDataMessageOutputMessageType type = OutputDataMessageOutputMessageType.UNKNOWN;

  public static final String SERIALIZED_NAME_DEVICE = "device";
  @SerializedName(SERIALIZED_NAME_DEVICE)
  private Device device;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private byte[] payload;

  public static final String SERIALIZED_NAME_RECEIVED = "received";
  @SerializedName(SERIALIZED_NAME_RECEIVED)
  private String received;

  public static final String SERIALIZED_NAME_TRANSPORT = "transport";
  @SerializedName(SERIALIZED_NAME_TRANSPORT)
  private String transport;

  public static final String SERIALIZED_NAME_UDP_META_DATA = "udpMetaData";
  @SerializedName(SERIALIZED_NAME_UDP_META_DATA)
  private UDPMetadata udpMetaData;

  public static final String SERIALIZED_NAME_COAP_META_DATA = "coapMetaData";
  @SerializedName(SERIALIZED_NAME_COAP_META_DATA)
  private CoAPMetadata coapMetaData;


  public OutputDataMessage type(OutputDataMessageOutputMessageType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OutputDataMessageOutputMessageType getType() {
    return type;
  }


  public void setType(OutputDataMessageOutputMessageType type) {
    this.type = type;
  }


  public OutputDataMessage device(Device device) {
    
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Device getDevice() {
    return device;
  }


  public void setDevice(Device device) {
    this.device = device;
  }


  public OutputDataMessage payload(byte[] payload) {
    
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public byte[] getPayload() {
    return payload;
  }


  public void setPayload(byte[] payload) {
    this.payload = payload;
  }


  public OutputDataMessage received(String received) {
    
    this.received = received;
    return this;
  }

   /**
   * Received time for message. Value is ms since epoch.
   * @return received
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Received time for message. Value is ms since epoch.")

  public String getReceived() {
    return received;
  }


  public void setReceived(String received) {
    this.received = received;
  }


  public OutputDataMessage transport(String transport) {
    
    this.transport = transport;
    return this;
  }

   /**
   * Get transport
   * @return transport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTransport() {
    return transport;
  }


  public void setTransport(String transport) {
    this.transport = transport;
  }


  public OutputDataMessage udpMetaData(UDPMetadata udpMetaData) {
    
    this.udpMetaData = udpMetaData;
    return this;
  }

   /**
   * Get udpMetaData
   * @return udpMetaData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UDPMetadata getUdpMetaData() {
    return udpMetaData;
  }


  public void setUdpMetaData(UDPMetadata udpMetaData) {
    this.udpMetaData = udpMetaData;
  }


  public OutputDataMessage coapMetaData(CoAPMetadata coapMetaData) {
    
    this.coapMetaData = coapMetaData;
    return this;
  }

   /**
   * Get coapMetaData
   * @return coapMetaData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CoAPMetadata getCoapMetaData() {
    return coapMetaData;
  }


  public void setCoapMetaData(CoAPMetadata coapMetaData) {
    this.coapMetaData = coapMetaData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputDataMessage outputDataMessage = (OutputDataMessage) o;
    return Objects.equals(this.type, outputDataMessage.type) &&
        Objects.equals(this.device, outputDataMessage.device) &&
        Arrays.equals(this.payload, outputDataMessage.payload) &&
        Objects.equals(this.received, outputDataMessage.received) &&
        Objects.equals(this.transport, outputDataMessage.transport) &&
        Objects.equals(this.udpMetaData, outputDataMessage.udpMetaData) &&
        Objects.equals(this.coapMetaData, outputDataMessage.coapMetaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, device, Arrays.hashCode(payload), received, transport, udpMetaData, coapMetaData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputDataMessage {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    received: ").append(toIndentedString(received)).append("\n");
    sb.append("    transport: ").append(toIndentedString(transport)).append("\n");
    sb.append("    udpMetaData: ").append(toIndentedString(udpMetaData)).append("\n");
    sb.append("    coapMetaData: ").append(toIndentedString(coapMetaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

