/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.ProtobufAny;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RuntimeStreamError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-20T10:26:47.664Z[GMT]")
public class RuntimeStreamError {
  public static final String SERIALIZED_NAME_GRPC_CODE = "grpcCode";
  @SerializedName(SERIALIZED_NAME_GRPC_CODE)
  private Integer grpcCode;

  public static final String SERIALIZED_NAME_HTTP_CODE = "httpCode";
  @SerializedName(SERIALIZED_NAME_HTTP_CODE)
  private Integer httpCode;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_HTTP_STATUS = "httpStatus";
  @SerializedName(SERIALIZED_NAME_HTTP_STATUS)
  private String httpStatus;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private List<ProtobufAny> details = null;


  public RuntimeStreamError grpcCode(Integer grpcCode) {
    
    this.grpcCode = grpcCode;
    return this;
  }

   /**
   * Get grpcCode
   * @return grpcCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getGrpcCode() {
    return grpcCode;
  }


  public void setGrpcCode(Integer grpcCode) {
    this.grpcCode = grpcCode;
  }


  public RuntimeStreamError httpCode(Integer httpCode) {
    
    this.httpCode = httpCode;
    return this;
  }

   /**
   * Get httpCode
   * @return httpCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getHttpCode() {
    return httpCode;
  }


  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }


  public RuntimeStreamError message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public RuntimeStreamError httpStatus(String httpStatus) {
    
    this.httpStatus = httpStatus;
    return this;
  }

   /**
   * Get httpStatus
   * @return httpStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHttpStatus() {
    return httpStatus;
  }


  public void setHttpStatus(String httpStatus) {
    this.httpStatus = httpStatus;
  }


  public RuntimeStreamError details(List<ProtobufAny> details) {
    
    this.details = details;
    return this;
  }

  public RuntimeStreamError addDetailsItem(ProtobufAny detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ProtobufAny> getDetails() {
    return details;
  }


  public void setDetails(List<ProtobufAny> details) {
    this.details = details;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuntimeStreamError runtimeStreamError = (RuntimeStreamError) o;
    return Objects.equals(this.grpcCode, runtimeStreamError.grpcCode) &&
        Objects.equals(this.httpCode, runtimeStreamError.httpCode) &&
        Objects.equals(this.message, runtimeStreamError.message) &&
        Objects.equals(this.httpStatus, runtimeStreamError.httpStatus) &&
        Objects.equals(this.details, runtimeStreamError.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grpcCode, httpCode, message, httpStatus, details);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuntimeStreamError {\n");
    sb.append("    grpcCode: ").append(toIndentedString(grpcCode)).append("\n");
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

