/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CollectionFirmwareFirmwareManagement
 */
public class CollectionFirmwareFirmwareManagementTest {
    /**
     * Model tests for CollectionFirmwareFirmwareManagement
     */
    @Test
    public void testCollectionFirmwareFirmwareManagement() {
        // TODO: test CollectionFirmwareFirmwareManagement
    }

}
