/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.CollectionFirmwareFirmwareManagement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CollectionFirmware
 */
public class CollectionFirmwareTest {
    private final CollectionFirmware model = new CollectionFirmware();

    /**
     * Model tests for CollectionFirmware
     */
    @Test
    public void testCollectionFirmware() {
        // TODO: test CollectionFirmware
    }

    /**
     * Test the property 'currentFirmwareId'
     */
    @Test
    public void currentFirmwareIdTest() {
        // TODO: test currentFirmwareId
    }

    /**
     * Test the property 'targetFirmwareId'
     */
    @Test
    public void targetFirmwareIdTest() {
        // TODO: test targetFirmwareId
    }

    /**
     * Test the property 'management'
     */
    @Test
    public void managementTest() {
        // TODO: test management
    }

}
