/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.CollectionFirmware;
import com.lab5e.span.model.FieldMask;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Collection
 */
public class CollectionTest {
    private final Collection model = new Collection();

    /**
     * Model tests for Collection
     */
    @Test
    public void testCollection() {
        // TODO: test Collection
    }

    /**
     * Test the property 'collectionId'
     */
    @Test
    public void collectionIdTest() {
        // TODO: test collectionId
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'fieldMask'
     */
    @Test
    public void fieldMaskTest() {
        // TODO: test fieldMask
    }

    /**
     * Test the property 'firmware'
     */
    @Test
    public void firmwareTest() {
        // TODO: test firmware
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
