/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FirmwareMetadata
 */
public class FirmwareMetadataTest {
    private final FirmwareMetadata model = new FirmwareMetadata();

    /**
     * Model tests for FirmwareMetadata
     */
    @Test
    public void testFirmwareMetadata() {
        // TODO: test FirmwareMetadata
    }

    /**
     * Test the property 'currentFirmwareId'
     */
    @Test
    public void currentFirmwareIdTest() {
        // TODO: test currentFirmwareId
    }

    /**
     * Test the property 'targetFirmwareId'
     */
    @Test
    public void targetFirmwareIdTest() {
        // TODO: test targetFirmwareId
    }

    /**
     * Test the property 'firmwareVersion'
     */
    @Test
    public void firmwareVersionTest() {
        // TODO: test firmwareVersion
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'modelNumber'
     */
    @Test
    public void modelNumberTest() {
        // TODO: test modelNumber
    }

    /**
     * Test the property 'manufacturer'
     */
    @Test
    public void manufacturerTest() {
        // TODO: test manufacturer
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateMessage'
     */
    @Test
    public void stateMessageTest() {
        // TODO: test stateMessage
    }

}
