/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NetworkMetadata
 */
public class NetworkMetadataTest {
    private final NetworkMetadata model = new NetworkMetadata();

    /**
     * Model tests for NetworkMetadata
     */
    @Test
    public void testNetworkMetadata() {
        // TODO: test NetworkMetadata
    }

    /**
     * Test the property 'allocatedIp'
     */
    @Test
    public void allocatedIpTest() {
        // TODO: test allocatedIp
    }

    /**
     * Test the property 'allocatedAt'
     */
    @Test
    public void allocatedAtTest() {
        // TODO: test allocatedAt
    }

    /**
     * Test the property 'cellId'
     */
    @Test
    public void cellIdTest() {
        // TODO: test cellId
    }

}
