/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OutputStatus
 */
public class OutputStatusTest {
    private final OutputStatus model = new OutputStatus();

    /**
     * Model tests for OutputStatus
     */
    @Test
    public void testOutputStatus() {
        // TODO: test OutputStatus
    }

    /**
     * Test the property 'collectionId'
     */
    @Test
    public void collectionIdTest() {
        // TODO: test collectionId
    }

    /**
     * Test the property 'outputId'
     */
    @Test
    public void outputIdTest() {
        // TODO: test outputId
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'errorCount'
     */
    @Test
    public void errorCountTest() {
        // TODO: test errorCount
    }

    /**
     * Test the property 'forwarded'
     */
    @Test
    public void forwardedTest() {
        // TODO: test forwarded
    }

    /**
     * Test the property 'received'
     */
    @Test
    public void receivedTest() {
        // TODO: test received
    }

    /**
     * Test the property 'retransmits'
     */
    @Test
    public void retransmitsTest() {
        // TODO: test retransmits
    }

}
