/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OutputConfig
 */
public class OutputConfigTest {
    private final OutputConfig model = new OutputConfig();

    /**
     * Model tests for OutputConfig
     */
    @Test
    public void testOutputConfig() {
        // TODO: test OutputConfig
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'basicAuthUser'
     */
    @Test
    public void basicAuthUserTest() {
        // TODO: test basicAuthUser
    }

    /**
     * Test the property 'basicAuthPass'
     */
    @Test
    public void basicAuthPassTest() {
        // TODO: test basicAuthPass
    }

    /**
     * Test the property 'customHeaderName'
     */
    @Test
    public void customHeaderNameTest() {
        // TODO: test customHeaderName
    }

    /**
     * Test the property 'customHeaderValue'
     */
    @Test
    public void customHeaderValueTest() {
        // TODO: test customHeaderValue
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    public void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'asIsPayload'
     */
    @Test
    public void asIsPayloadTest() {
        // TODO: test asIsPayload
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    public void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'disableCertCheck'
     */
    @Test
    public void disableCertCheckTest() {
        // TODO: test disableCertCheck
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'topicName'
     */
    @Test
    public void topicNameTest() {
        // TODO: test topicName
    }

}
