/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.CoAPMetadata;
import com.lab5e.span.model.Device;
import com.lab5e.span.model.OutputDataMessageOutputMessageType;
import com.lab5e.span.model.UDPMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OutputDataMessage
 */
public class OutputDataMessageTest {
    private final OutputDataMessage model = new OutputDataMessage();

    /**
     * Model tests for OutputDataMessage
     */
    @Test
    public void testOutputDataMessage() {
        // TODO: test OutputDataMessage
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'device'
     */
    @Test
    public void deviceTest() {
        // TODO: test device
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'received'
     */
    @Test
    public void receivedTest() {
        // TODO: test received
    }

    /**
     * Test the property 'transport'
     */
    @Test
    public void transportTest() {
        // TODO: test transport
    }

    /**
     * Test the property 'udpMetaData'
     */
    @Test
    public void udpMetaDataTest() {
        // TODO: test udpMetaData
    }

    /**
     * Test the property 'coapMetaData'
     */
    @Test
    public void coapMetaDataTest() {
        // TODO: test coapMetaData
    }

}
