/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.0.12 reported-davon
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.ProtobufAny;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RuntimeStreamError
 */
public class RuntimeStreamErrorTest {
    private final RuntimeStreamError model = new RuntimeStreamError();

    /**
     * Model tests for RuntimeStreamError
     */
    @Test
    public void testRuntimeStreamError() {
        // TODO: test RuntimeStreamError
    }

    /**
     * Test the property 'grpcCode'
     */
    @Test
    public void grpcCodeTest() {
        // TODO: test grpcCode
    }

    /**
     * Test the property 'httpCode'
     */
    @Test
    public void httpCodeTest() {
        // TODO: test httpCode
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'httpStatus'
     */
    @Test
    public void httpStatusTest() {
        // TODO: test httpStatus
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

}
