/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.FirmwareMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateDeviceRequest
 */
public class UpdateDeviceRequestTest {
    private final UpdateDeviceRequest model = new UpdateDeviceRequest();

    /**
     * Model tests for UpdateDeviceRequest
     */
    @Test
    public void testUpdateDeviceRequest() {
        // TODO: test UpdateDeviceRequest
    }

    /**
     * Test the property 'existingCollectionId'
     */
    @Test
    public void existingCollectionIdTest() {
        // TODO: test existingCollectionId
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    public void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'collectionId'
     */
    @Test
    public void collectionIdTest() {
        // TODO: test collectionId
    }

    /**
     * Test the property 'imsi'
     */
    @Test
    public void imsiTest() {
        // TODO: test imsi
    }

    /**
     * Test the property 'imei'
     */
    @Test
    public void imeiTest() {
        // TODO: test imei
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'firmware'
     */
    @Test
    public void firmwareTest() {
        // TODO: test firmware
    }

}
